site_name: Retirement Income Toolkit
theme:
  name: material
  palette:
    scheme: deep purple
  features:
    - navigation.tabs
    - content.code.annotate
repo_url: https://github.com/print-hi/retirement-toolkit


pages:
  - Home: 'index.md'
nav:
  - Overview:
    - 'Getting Started': 'Home/start.md'
    - 'About': Home/about.md'
    - 'Changelog': 'Home/log.md'
  - Policy Valuation:
    - 'Policy Valuation/overview.md'
    - 'Policy Valuation/top1.md'
    - 'Policy Valuation/top2.md'
    - 'Policy Valuation/top3.md'
  - Aggregate Mortality:
    - 'Aggregate Mortality/overview.md'
    - 'Aggregate Mortality/age_completion.md'
    - 'Aggregate Mortality/rate_change.md'
    - 'Aggregate Mortality/risk_neutral.md'
    - 'Aggregate Mortality/stats_functions.md'
  - Health State:
    - 'Health State 3/overview.md'
    - 'Health State 3/cox_model.md'
    - 3-State Model:
      - 'Health State 3/trans_probs.md'
      - 'Health State 3/lifetable.md'
      - 'Health State 3/simulation.md'
      - 'Health State 3/stats.md'
    - 'Health State 5/overview.md'
    - 'Health State 5/cox_model.md'
    - 5-State Model:
      - 'Health State 5/trans_probs.md'
      - 'Health State 5/lifetable.md'
      - 'Health State 5/simulation.md'
      - 'Health State 5/stats.md'
  - Economic Scenario Generator:
    - 'Economic Scenario Generator/overview.md'
    - 'Economic Scenario Generator/discrete_esg.md'
    - 'Economic Scenario Generator/cts_esg.md'
    - 'Economic Scenario Generator/top3.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  
  - pymdownx.arithmatex:
      generic: true
  - codehilite
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
      
# for pymdown.arithmatex 
extra_javascript:
  - 'expand.js'
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
