site_name: Retirement Income Toolkit
theme:
  name: material
  palette:
    scheme: deep purple
  features:
    - navigation.tabs
    - content.code.annotate
repo_url: https://github.com/print-hi/retirement-toolkit


nav:
- Home: 
  - 'Home/index.md'
  - 'Home/start.md'
  - 'Home/log.md'
  - 'Home/about.md'
- Policy Valuation:
  - 'Policy Valuation/overview.md'
  - 'Policy Valuation/top1.md'
  - 'Policy Valuation/top2.md'
  - 'Policy Valuation/top3.md'
- Aggregate Mortality:
  - 'Aggregate Mortality/overview.md'
  - 'Aggregate Mortality/top1.md'
  - 'Aggregate Mortality/top2.md'
  - 'Aggregate Mortality/top3.md'
- Health State 3:
  - 'Health State 3/overview.md'
  - 'Health State 3/cox_model.md'
  - Getting Started:
      - 'Health State 3/trans_probs.md'
      - 'Health State 3/lifetable.md'
      - 'Health State 3/simulation.md'
  - 'Health State 3/stats.md'
- Health State 5:
  - 'Health State 5/overview.md'
  - 'Health State 5/cox_model.md'
  - Getting Started:
      - 'Health State 5/trans_probs.md'
      - 'Health State 5/lifetable.md'
      - 'Health State 5/simulation.md'
- Economic Scenario Generator:
  - 'Economic Scenario Generator/overview.md'
  - 'Economic Scenario Generator/top1.md'
  - 'Economic Scenario Generator/top2.md'
  - 'Economic Scenario Generator/top3.md'


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  
  - pymdownx.arithmatex:
      generic: true
  - codehilite
  - pymdownx.details
  - admonition
      
# for pymdown.arithmatex 
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
